### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by MCTyler** [Rammelkast/SpawnJoin#1]
Is this code supposed to be build able? I built it and it doesn't do anything. The Plugin.yml is totally wrong, and even after I fixed that and compiled it it still will not do anything on the server. It loads but it's just empty.

**Comment by Rammelkast** [comment]
Have you tried compiling from the subfolder SpawnJoin?

**Comment by MCTyler** [comment]
Yea, I guess...I'm new to compiling but I loaded the zip file in Eclipse and added the 2 dependencies and exported to the Jar. Guess I did it wrong.

**Comment by Rammelkast** [comment]
If you want the JAR, you can download it from the jenkins: http://web1.rammelkast.nl:8080/
